version: "3.5"
services:
  pyping:
    image: pyping:latest
    container_name: pyping
    expose:
      - 80
    environment:
      FLASK_ENV: "production"
      INSIDE_CONTAINER: "true"
      MONGODB_USERNAME: "root"
      MONGODB_PASSWORD: "mongo_pw"
      MONGODB_DATABASE: "db"
      MONGODB_HOSTNAME: "mongodb"
      FLASK_SECRET: "secret-flask-key"
    volumes:
      - ./app/config:/app/config
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./app
      
  agent:
    expose:
      - "6768"
    container_name: agent
    image: agent
    network_mode: host
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./agent
    
  cron:
    container_name: cron
    image: cron:latest
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./cron
      
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "mongo_pw"
      MONGO_INITDB_DATABASE: "db"
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodb-pyping:/data/db
    restart: unless-stopped
          
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped

    
volumes:
  mongodb-pyping:
